blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/philippleidig/twincatbsd-package-repository-history/discussions
    about: Ask questions and discuss ideas
